// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCourse.Infrastructure.Data;

#nullable disable

namespace WebCourse.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebCourse.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VillaDB");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Muhteşem deniz manzarasına sahip, geniş bahçeli ve özel havuzlu lüks villa.",
                            ImageUrl = "https://example.com/villa1.jpg",
                            Name = "Deniz Manzaralı Lüks Villa",
                            Occupancy = 8,
                            Price = 1500000.0,
                            Sqft = 3500,
                            Updated_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Created_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Doğayla iç içe, huzurlu bir ortamda bulunan, orman manzaralı villa.",
                            ImageUrl = "https://example.com/villa2.jpg",
                            Name = "Orman İçinde Sakin Villa",
                            Occupancy = 6,
                            Price = 950000.0,
                            Sqft = 2200,
                            Updated_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Created_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Şehir merkezine kolay ulaşım sağlayan, modern tasarımlı ve geniş teraslı villa.",
                            ImageUrl = "https://example.com/villa3.jpg",
                            Name = "Şehir Merkezine Yakın Modern Villa",
                            Occupancy = 7,
                            Price = 1200000.0,
                            Sqft = 2800,
                            Updated_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebCourse.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("int");

                    b.Property<string>("specialProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("villaID")
                        .HasColumnType("int");

                    b.HasKey("Villa_Number");

                    b.HasIndex("villaID");

                    b.ToTable("VillaNumberDB");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            villaID = 1
                        },
                        new
                        {
                            Villa_Number = 102,
                            villaID = 1
                        },
                        new
                        {
                            Villa_Number = 103,
                            villaID = 1
                        },
                        new
                        {
                            Villa_Number = 201,
                            villaID = 2
                        },
                        new
                        {
                            Villa_Number = 202,
                            villaID = 2
                        },
                        new
                        {
                            Villa_Number = 203,
                            villaID = 2
                        },
                        new
                        {
                            Villa_Number = 301,
                            villaID = 3
                        },
                        new
                        {
                            Villa_Number = 302,
                            villaID = 3
                        },
                        new
                        {
                            Villa_Number = 303,
                            villaID = 3
                        });
                });

            modelBuilder.Entity("WebCourse.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("WebCourse.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("villaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
